### ISSUE TITLE
Cannot populate dashboard with data

### ISSUE THREAD

**Issue by ArneAnka** [arpanghosh8453/fitbit-web-ui-app#9]
Using docker compose

```
services:
    fitbit-ui:
        image: 'thisisarpanghosh/fitbit-report-app:latest'
        container_name: 'fitbit-report-app'
        ports:
            - "5001:80"
        restart: unless-stopped
```

Tried the default values for date range. aug 8 2023 - aug 2 2024. Tried smaller intervaller as well, same error.

Followed instructions on how to configure app in the fitbit dev portal. Got an API access token.

```
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
fitbit-report-app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 1265, in dispatch
fitbit-report-app  |     ctx.run(
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
fitbit-report-app  |     output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
fitbit-report-app  |   File "/app/src/app.py", line 273, in update_output
fitbit-report-app  |     report_title = "Wellness Report - " + user_profile["user"]["firstName"] + " " + user_profile["user"]["lastName"]
fitbit-report-app  | KeyError: 'firstName'
fitbit-report-app  | [2024-08-02 04:42:13 +0000] [1] [INFO] Handling signal: term
fitbit-report-app  | [2024-08-02 04:42:13 +0000] [7] [INFO] Worker exiting (pid: 7)
fitbit-report-app  | [2024-08-02 04:42:13 +0000] [1] [INFO] Shutting down: Master
fitbit-report-app  | [2024-08-02 04:42:24 +0000] [1] [INFO] Starting gunicorn 22.0.0
fitbit-report-app  | [2024-08-02 04:42:24 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
fitbit-report-app  | [2024-08-02 04:42:24 +0000] [1] [INFO] Using worker: sync
fitbit-report-app  | [2024-08-02 04:42:24 +0000] [7] [INFO] Booting worker with pid: 7
fitbit-report-app  | [2024-08-02 04:42:34,985] ERROR in app: Exception on /_dash-update-component [POST]
fitbit-report-app  | Traceback (most recent call last):
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
fitbit-report-app  |     response = self.full_dispatch_request()
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
fitbit-report-app  |     rv = self.handle_user_exception(e)
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
fitbit-report-app  |     rv = self.dispatch_request()
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
fitbit-report-app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 1265, in dispatch
fitbit-report-app  |     ctx.run(
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
fitbit-report-app  |     output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
fitbit-report-app  |   File "/app/src/app.py", line 265, in update_output
fitbit-report-app  |     response_heartrate = response_heartrate + requests.get("https://api.fitbit.com/1/user/-/activities/heart/date/"+ temp_start_date +"/"+ temp_end_date +".json", headers=headers).json()['activities-heart']
fitbit-report-app  | KeyError: 'activities-heart'
fitbit-report-app  | [2024-08-02 04:43:07,191] ERROR in app: Exception on /_dash-update-component [POST]
fitbit-report-app  | Traceback (most recent call last):
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
fitbit-report-app  |     response = self.full_dispatch_request()
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
fitbit-report-app  |     rv = self.handle_user_exception(e)
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
fitbit-report-app  |     rv = self.dispatch_request()
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
fitbit-report-app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 1265, in dispatch
fitbit-report-app  |     ctx.run(
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
fitbit-report-app  |     output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
fitbit-report-app  |   File "/app/src/app.py", line 265, in update_output
fitbit-report-app  |     response_heartrate = response_heartrate + requests.get("https://api.fitbit.com/1/user/-/activities/heart/date/"+ temp_start_date +"/"+ temp_end_date +".json", headers=headers).json()['activities-heart']
fitbit-report-app  | KeyError: 'activities-heart'
```

**Comment by arpanghosh8453** [comment]
Hello, Thanks for reaching out. Did you make sure to register the app as `personal` type so it gets access to intraday data? 

try out this curl command given below with replacing `<your API key>` with your API key and see if that works (to ensure your API key has access to intraday HR data. 

`curl -X GET "https://api.fitbit.com/1/user/-/activities/heart/date/2024-08-01/1d/1min.json" -H "accept: application/json" -H "authorization: Bearer <your API key>"`

You can perform authorization (Click on the Authorize button on the top right first before trying out commands) and obtain a temporary API key from here too : https://dev.fitbit.com/build/reference/web-api/explore/

Let me know if that solves your problem.

**Comment by ArneAnka** [comment]
Thanks for your reply.

I changed to `personal`.

When i tried the curl command, i got a response, so the API token seems to be working.

But application will not populate the dashboard. I got this (different) error in docker:

```
fitbit-report-app  | Traceback (most recent call last):
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
fitbit-report-app  |     response = self.full_dispatch_request()
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
fitbit-report-app  |     rv = self.handle_user_exception(e)
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
fitbit-report-app  |     rv = self.dispatch_request()
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
fitbit-report-app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 1265, in dispatch
fitbit-report-app  |     ctx.run(
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
fitbit-report-app  |     output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
fitbit-report-app  |   File "/app/src/app.py", line 273, in update_output
fitbit-report-app  |     report_title = "Wellness Report - " + user_profile["user"]["firstName"] + " " + user_profile["user"]["lastName"]
fitbit-report-app  | KeyError: 'firstName'
fitbit-report-app  | [2024-08-02 05:35:56,321] ERROR in app: Exception on /_dash-update-component [POST]
fitbit-report-app  | Traceback (most recent call last):
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
fitbit-report-app  |     response = self.full_dispatch_request()
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
fitbit-report-app  |     rv = self.handle_user_exception(e)
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
fitbit-report-app  |     rv = self.dispatch_request()
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
fitbit-report-app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 1265, in dispatch
fitbit-report-app  |     ctx.run(
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
fitbit-report-app  |     output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
fitbit-report-app  |   File "/app/src/app.py", line 273, in update_output
fitbit-report-app  |     report_title = "Wellness Report - " + user_profile["user"]["firstName"] + " " + user_profile["user"]["lastName"]
fitbit-report-app  | KeyError: 'firstName'
fitbit-report-app  | [2024-08-02 05:36:28,051] ERROR in app: Exception on /_dash-update-component [POST]
fitbit-report-app  | Traceback (most recent call last):
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
fitbit-report-app  |     response = self.full_dispatch_request()
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
fitbit-report-app  |     rv = self.handle_user_exception(e)
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
fitbit-report-app  |     rv = self.dispatch_request()
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
fitbit-report-app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 1265, in dispatch
fitbit-report-app  |     ctx.run(
fitbit-report-app  |   File "/usr/local/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
fitbit-report-app  |     output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
fitbit-report-app  |   File "/app/src/app.py", line 273, in update_output
fitbit-report-app  |     report_title = "Wellness Report - " + user_profile["user"]["firstName"] + " " + user_profile["user"]["lastName"]
fitbit-report-app  | KeyError: 'firstName'
```

**Comment by arpanghosh8453** [comment]
Looks like you don't have a registered `Firstname` and/or `Lastname` in your account. Did you make sure you have your profile complete on fitbit?

**Comment by ArneAnka** [comment]
I have a complete profile, what i can tell, on https://www.fitbit.com/settings/profile.

No lastname option, just "name".

**Comment by arpanghosh8453** [comment]
Can you try out this and see what's the result?

`curl -X GET "https://api.fitbit.com/1/user/-/profile.json" -H "accept: application/json" -H "authorization: Bearer <your API key>"`

**Comment by arpanghosh8453** [comment]
@ArneAnka This is very interesting indeed. All the user I have encountered before had a `firstname` and `lastname` parameter in the json response instead of `fullname` that you have. I am assuming you have linked your Google account to Fitbit account?

Anyway, the solution I have for you is find the python script inside the docker container (inside the /app folder), and replace the following line `report_title = "Wellness Report - " + user_profile["user"]["firstName"] + " " + user_profile["user"]["lastName"]` with `report_title = "Wellness Report - " + user_profile["user"]["fullName"]`

That should take care of the current issue. Let me know if that works out.

**Comment by ArneAnka** [comment]
Hi

No, i havent linked my google account with fitbit.

Changed the line and i got a great report. Thanks

**Comment by arpanghosh8453** [comment]
@ArneAnka Thank you for letting me know. It looks like accounts not linked with Google will have this issue. Is so the above fix will work for them (given they are self-hosting)
